// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Uptime.webser {
    
}


[System.ServiceModel.ServiceContractAttribute(Namespace="Uptime.webser", ConfigurationName="CurrencyConvertorSoap")]
public interface CurrencyConvertorSoap {
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://www.webserviceX.NET/ConversionRate")]
    double ConversionRate(www.webservicex.net.FromCurrency FromCurrency, www.webservicex.net.FromCurrency ToCurrency);
    
    [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="http://www.webserviceX.NET/ConversionRate", AsyncPattern=true)]
    System.IAsyncResult BeginConversionRate(www.webservicex.net.FromCurrency FromCurrency, www.webservicex.net.FromCurrency ToCurrency, System.AsyncCallback asyncCallback, object userState);
    
    double EndConversionRate(System.IAsyncResult result);
}

public interface CurrencyConvertorSoapChannel : CurrencyConvertorSoap, System.ServiceModel.IClientChannel {
}

public class CurrencyConvertorSoapClient : System.ServiceModel.ClientBase<CurrencyConvertorSoap>, CurrencyConvertorSoap {
    
    public CurrencyConvertorSoapClient() {
    }
    
    public CurrencyConvertorSoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public CurrencyConvertorSoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public CurrencyConvertorSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public CurrencyConvertorSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress endpoint) : 
            base(binding, endpoint) {
    }
    
    public double ConversionRate(www.webservicex.net.FromCurrency FromCurrency, www.webservicex.net.FromCurrency ToCurrency) {
        return base.Channel.ConversionRate(FromCurrency, ToCurrency);
    }
    
    public System.IAsyncResult BeginConversionRate(www.webservicex.net.FromCurrency FromCurrency, www.webservicex.net.FromCurrency ToCurrency, System.AsyncCallback asyncCallback, object userState) {
        return base.Channel.BeginConversionRate(FromCurrency, ToCurrency, asyncCallback, userState);
    }
    
    public double EndConversionRate(System.IAsyncResult result) {
        return base.Channel.EndConversionRate(result);
    }
}
namespace www.webservicex.net {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Currency", Namespace="http://www.webserviceX.NET/")]
    public enum FromCurrency {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AFA,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALL,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DZD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ARS,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AWG,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AUD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BSD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BHD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BDT,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BBD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BZD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BMD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BTN,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BOB,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BWP,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BRL,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GBP,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BND,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BIF,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XOF,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XAF,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KHR,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CAD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CVE,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KYD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLP,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CNY,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COP,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KMF,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CRC,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HRK,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CUP,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CYP,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CZK,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DKK,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DJF,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOP,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XCD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EGP,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SVC,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EEK,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ETB,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EUR,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FKP,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GHC,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GIP,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XAU,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GTQ,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GNF,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GYD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HTG,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HNL,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HKD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HUF,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ISK,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INR,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IDR,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IQD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ILS,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JMD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JPY,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JOD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KZT,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KES,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KRW,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KWD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LAK,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LVL,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LBP,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LSL,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LRD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LYD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LTL,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MOP,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MKD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MGF,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MWK,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MYR,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MVR,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTL,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MRO,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MUR,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MXN,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MDL,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNT,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MAD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MZM,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MMK,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NAD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NPR,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ANG,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NZD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NIO,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NGN,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KPW,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOK,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OMR,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XPF,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PKR,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XPD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAB,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PGK,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PYG,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PEN,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PHP,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XPT,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PLN,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QAR,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ROL,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RUB,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WST,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SAR,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SCR,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SLL,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XAG,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SGD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SKK,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SIT,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SBD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SOS,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZAR,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LKR,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SHP,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SDD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SRG,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SZL,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SEK,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CHF,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SYP,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TWD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TZS,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        THB,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TOP,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TTD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TND,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TRL,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        USD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AED,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UGX,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UAH,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UYU,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VUV,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VEB,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VND,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YER,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YUM,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZMK,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZWD,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TRY,
    }
}
